{% set name = "pypsa" %}
{% set version = "0.24.0" %}
{% set sha256 = "c29208cd573966b5834c8c6f032800e9306fab39f102a78b56212f450dfd86aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vvv '
  noarch: python

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - cartopy >=0.16
    - matplotlib-base
    - networkx >=1.10
    - numpy
    - pandas >=0.24.0
    - pyomo >=5.7
    - python >=3.9
    - scipy
    - six >=1.13.0
    - netcdf4
    - pytables
    - deprecation
    - validators
    - packaging
    - xarray
    - linopy >=0.2

test:
  imports:
    - pypsa

about:
  home: https://pypsa.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Python for Power Systems Analysis
  description: |
    PyPSA is a free software toolbox for simulating and optimising modern power
    systems that include features such as conventional generators with unit
    commitment, variable wind and solar generation, storage units, coupling to
    other energy sectors, and mixed alternating and direct current networks.
    PyPSA is designed to scale well with large networks and long time series.
  doc_url: https://pypsa.readthedocs.io
  dev_url: https://github.com/PyPSA/PyPSA

extra:
  recipe-maintainers:
    - coroa
    - nworbmot
    - fneum
